Repository CIT-NakamuraLab/project-alpha-rs, pull requests merged in 2023-03, with the labels that each got.

#2 NFCリーダーの読み出しとシリアル通信での問い合わせを結合
  src/main.py
  src/reader.py
Labels: feature / 機能追加

#3 受け渡すデータフォーマットの変更
  README.md
  src/controller.py
Labels: feature / 機能追加

#4 NFCリーダーの処理を最適化
  src/reader.py
Labels: bug / バグ

#6 シリアルデータが不正な場合のリーダー側のハンドリングを改善
  src/controller.py
  src/main.py
  src/reader.py
Labels: bug / バグ

#8 nfcリーダーの名前を固定する設定ファイルを追加
  udev-config/98-nfc.rules
Labels: documentation / ドキュメント
